// Build information, automatically generated by `ng-info`
const build = {
    version: "0.0.0",
    timestamp: "Thu May 06 2021 14:46:08 GMT-0300 (Horário Padrão de Brasília)",
    message: null,
    git: {
        user: "brunolima97",
        branch: "master",
        hash: "4f21b6",
        fullHash: "4f21b649c24933432d9cbcd005edc839f2374381"
    }
};

export default build;