// Build information, automatically generated by `ng-info`
const build = {
    version: "0.0.0",
    timestamp: "Thu Apr 29 2021 12:28:19 GMT-0300 (Horário Padrão de Brasília)",
    message: null,
    git: {
        user: "brunolima97",
        branch: "master",
        hash: "917284",
        fullHash: "917284b01049004fda1e7a50cc1e932e39848b07"
    }
};

export default build;